### ISSUE TITLE
Installation description issues

### ISSUE THREAD

**Issue by vitknobloch** [ctu-mrs/CTopPRM#2]
When installing I faced a couple issues with versions and missing dependencies, but it's a quick fix:
- gitman must be installed with pip. ```pip install gitman```
- scikit-learn is missing from dependencies for map.py script, but is required. ```pip install scikit-learn```
- setuptools version < 58.0.0 is needed for demjson to install (one of the subdependencies of map.py script). ```pip install setuptools~=57.5.0```

**Comment by novosma** [comment]
Thank you a lot for this! Added to the README!
