### ISSUE TITLE
Why the model seems need a rotation?

### ISSUE THREAD

**Issue by HouxiongYao** [ctu-mrs/CTopPRM#5]
I have run the code with 1-3-1.obj ,and  belowing is the results:
![图片](https://github.com/ctu-mrs/CTopPRM/assets/138581552/d5f0294d-db18-4563-b74f-cd84e481f43e)
If I delete 1-3-1.obj,here is the paths:
![图片](https://github.com/ctu-mrs/CTopPRM/assets/138581552/9a2deb53-28d4-4670-aaca-dc86111c92e0)
It seems like that if rotate the paths 90 degrees, the visualization will be just perfect. But I really don't know the reason or how to fix it.

**Comment by penickar** [comment]
When you import an obj file to the Blender you need to specify transform to be Y Forward and Z Up, see here:
![obj_import_transform](https://github.com/ctu-mrs/CTopPRM/assets/7031810/248a0824-87c3-4e54-babd-8586ea153aae)

**Comment by HouxiongYao** [comment]
> When you import an obj file to the Blender you need to specify transform to be Y Forward and Z Up, see here: ![obj_import_transform](https://private-user-images.githubusercontent.com/7031810/292917534-248a0824-87c3-4e54-babd-8586ea153aae.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NDc0OTMsIm5iZiI6MTcwMzY0NzE5MywicGF0aCI6Ii83MDMxODEwLzI5MjkxNzUzNC0yNDhhMDgyNC04N2MzLTRlNTQtYmFiZC04NTg2ZWExNTNhYWUuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjdUMDMxOTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDc2MjJhZTY4YjgwY2Q4OTY2MTM4YzE3MjA1OWI3YzY2YjE0ZGFjY2E4ZDA5NzEyNzczZWU0ZjdhZjg0ODk0OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ctvdbcxjw7___FiFq6_WhDbpaTLQHHFCGrYKHDeedv8)

Thank you! This method successfully solved my problem！
